services:
    owasp:
        build:
            context: .
        ports:
            - "8080:3000"
        environment:
            - MYSQL_HOST=mysql
            - MYSQL_USER=user
            - MYSQL_PASSWORD=password
            - MYSQL_NAME=owasp
            - MYSQL_PORT=3306
        volumes:
            - ./owasp:/usr/src/owasp
        networks:
            - mynetwork
        depends_on:
            - mysql
    mysql:
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: owasp
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        ports:
            - "3306:3306"
        networks:
            - mynetwork
volumes:
    mysql_data:
        driver: local
networks:
    mynetwork:
        driver: bridge
