services:
    owasp:
        build:
            context: .
        ports:
            - "443:5000"
        environment:
            MYSQL_HOST: mysql
            MYSQL_USER: user
            MYSQL_PASSWORD: RHZ1mpY1xxsPnD
            MYSQL_DATABASE: owasp
            VAULT_SERVER_URL: http://vault:5001
            JWT_SECRET: i@9|[D"/L(#9(=CJh2C=JIl5{@bFY9Kkg"{X2l-Y-?9qa@fX9@c6oA|R'Zz=,?.V
        networks:
            - mynetwork
        healthcheck:
            test: wget -O - 'https://127.0.0.1:5000/health' --no-check-certificate
            start_period: 5s
            interval: 10s
            timeout: 5s
            retries: 50
        depends_on:
            mysql:
                condition: service_healthy
            vault:
                condition: service_healthy
    mysql:
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: xx9c7Z9idjzaJ9
            MYSQL_DATABASE: owasp
            MYSQL_USER: user
            MYSQL_PASSWORD: RHZ1mpY1xxsPnD
        healthcheck:
            test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
            start_period: 5s
            interval: 5s
            timeout: 5s
            retries: 55
        networks:
            - mynetwork

    vault:
        build:
            context: ./src/vault
        networks:
            - mynetwork
        depends_on:
            mysqlvault:
                condition: service_healthy
        environment:
            MYSQL_HOST: mysqlvault
            MYSQL_USER: user
            MYSQL_PASSWORD: RHZ1mpY1xxsPnD
            MYSQL_DATABASE: vault
        healthcheck:
            test: wget -O - 'http://127.0.0.1:5001/health'
            start_period: 5s
            interval: 10s
            timeout: 5s
            retries: 50
    mysqlvault:
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: xx9c7Z9idjzaJ9
            MYSQL_DATABASE: vault
            MYSQL_USER: user
            MYSQL_PASSWORD: RHZ1mpY1xxsPnD
        healthcheck:
            test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
            start_period: 5s
            interval: 5s
            timeout: 5s
            retries: 55
        networks:
            - mynetwork
    trafficgenerator:
        build:
            context: ./src/traffic_generator
        networks:
            - mynetwork
        environment:
            SERVER_HOST: owasp
            SERVER_PORT: 5000
        depends_on:
            owasp:
                condition: service_healthy
volumes:
    mysql_data:
        driver: local
networks:
    mynetwork:
        driver: bridge
