import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Vaultium",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="w-full px-6 py-4 flex justify-between items-center bg-blue-600 text-white shadow-md">
          <div className="flex items-center gap-2">
            <span className="text-lg font-bold">Bank</span>
          </div>
          <nav className="flex gap-6 text-sm sm:text-base">
            <a href=".." className="hover:underline">Home</a>
            <a href="/about" className="hover:underline">Our Employees</a>
            <a href="/login" className="hover:underline">Login</a>
            <a href="/forget" className="hover:underline">Forgot Password</a>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
